[project]
name = "management-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "langchain-openai>=0.3.29",
    "langgraph>=0.6.4",
    "uvicorn[standard]>=0.35.0",
]
